"""empty message

Revision ID: 01c3503a030b
Revises: 775db29c683f
Create Date: 2020-07-24 09:57:54.190867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01c3503a030b'
down_revision = '775db29c683f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tobe_type', sa.SmallInteger(), nullable=True, comment='邀请后成为的类型，对应member_cards中的member_type'),
    sa.Column('tobe_level', sa.SmallInteger(), nullable=True, comment='邀请后成为的等级，对应member_cards中的grade'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='邀请码'),
    sa.Column('manager_customer_id', sa.String(length=64), nullable=True, comment='管理者ID'),
    sa.Column('used_customer_id', sa.String(length=64), nullable=True, comment='使用者ID'),
    sa.Column('new_member_card_id', sa.String(length=64), nullable=True, comment='开卡id'),
    sa.Column('creator_id', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='如果不为空，则表示已经使用，软删除'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['new_member_card_id'], ['member_cards.id'], ),
    sa.ForeignKeyConstraint(['used_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('sku', sa.Column('agent_first_rebate', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='一级代理商返佣'))
    op.add_column('sku', sa.Column('agent_second_rebate', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='二级代理商返佣'))
    op.add_column('sku', sa.Column('could_get_coupon_id', sa.String(length=64), nullable=True))
    op.add_column('sku', sa.Column('score', sa.Integer(), nullable=True, comment='积分'))
    op.add_column('sku', sa.Column('score_type', sa.SmallInteger(), nullable=True, comment='是否可用积分'))
    op.create_foreign_key(None, 'sku', 'coupons', ['could_get_coupon_id'], ['id'])
    op.drop_column('sku', 'score_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('score_types', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否可用积分'))
    op.drop_constraint(None, 'sku', type_='foreignkey')
    op.drop_column('sku', 'score_type')
    op.drop_column('sku', 'score')
    op.drop_column('sku', 'could_get_coupon_id')
    op.drop_column('sku', 'agent_second_rebate')
    op.drop_column('sku', 'agent_first_rebate')
    op.drop_table('invitation_code')
    # ### end Alembic commands ###
