"""empty message

Revision ID: 0fff0cb1d2ac
Revises: 826ea9f271cd
Create Date: 2020-04-29 22:28:26.118491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fff0cb1d2ac'
down_revision = '826ea9f271cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('combo_price', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='仅当活动类型是4时生效, 添加的sku为活动范围，添加的gifts为这个sku套餐的其它sku'))
    op.add_column('benefits', sa.Column('presell_multiple', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='预售定金倍数，例如定金是10元，倍数是1.5，那么抵扣商品15元'))
    op.add_column('benefits', sa.Column('presell_price', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='当类型是5时， 设置预售定金'))
    op.drop_column('promotions', 'combo_price')
    op.drop_column('promotions', 'presell_price')
    op.drop_column('promotions', 'presell_multiple')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('presell_multiple', mysql.DECIMAL(precision=3, scale=2), nullable=True, comment='预售定金倍数，例如定金是10元，倍数是1.5，那么抵扣商品15元'))
    op.add_column('promotions', sa.Column('presell_price', mysql.DECIMAL(precision=7, scale=2), nullable=True, comment='当类型是5时， 设置预售定金'))
    op.add_column('promotions', sa.Column('combo_price', mysql.DECIMAL(precision=7, scale=2), nullable=True, comment='仅当活动类型是4时生效, 只允许添加sku'))
    op.drop_column('benefits', 'presell_price')
    op.drop_column('benefits', 'presell_multiple')
    op.drop_column('benefits', 'combo_price')
    # ### end Alembic commands ###
