"""empty message

Revision ID: 10ef7a5c6c72
Revises: d841da0ab3c1
Create Date: 2020-07-26 09:38:53.676513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ef7a5c6c72'
down_revision = 'd841da0ab3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('contents', sa.Text(length=4294967295), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'contents')
    # ### end Alembic commands ###
