"""empty message

Revision ID: 13c4d77c0730
Revises: 6a0f4b34f731
Create Date: 2020-07-15 09:16:04.416649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c4d77c0730'
down_revision = '6a0f4b34f731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_openid', table_name='customers')
    op.create_index(op.f('ix_customers_openid'), 'customers', ['openid'], unique=False)
    op.drop_index('ix_customers_unionid', table_name='customers')
    op.create_index(op.f('ix_customers_unionid'), 'customers', ['unionid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_unionid'), table_name='customers')
    op.create_index('ix_customers_unionid', 'customers', ['unionid'], unique=True)
    op.drop_index(op.f('ix_customers_openid'), table_name='customers')
    op.create_index('ix_customers_openid', 'customers', ['openid'], unique=True)
    # ### end Alembic commands ###
