"""empty message

Revision ID: 1cfc057bb8da
Revises: 7a9526461f0e
Create Date: 2020-07-14 13:44:06.224034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfc057bb8da'
down_revision = '7a9526461f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obj_storage',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('obj_key', sa.String(length=64), nullable=False),
    sa.Column('obj_type', sa.SmallInteger(), nullable=True, comment='0 图片，1 视频， 2 文本'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obj_storage_bucket'), 'obj_storage', ['bucket'], unique=False)
    op.create_index(op.f('ix_obj_storage_obj_key'), 'obj_storage', ['obj_key'], unique=False)
    op.create_index(op.f('ix_obj_storage_region'), 'obj_storage', ['region'], unique=False)
    op.create_table('banners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='banner的名称'),
    sa.Column('order', sa.SmallInteger(), nullable=True, comment='排序，若相同则无序'),
    sa.Column('objects', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True, comment='用于存放点击后跳转的链接'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['objects'], ['obj_storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_name'), 'banners', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banners_name'), table_name='banners')
    op.drop_table('banners')
    op.drop_index(op.f('ix_obj_storage_region'), table_name='obj_storage')
    op.drop_index(op.f('ix_obj_storage_obj_key'), table_name='obj_storage')
    op.drop_index(op.f('ix_obj_storage_bucket'), table_name='obj_storage')
    op.drop_table('obj_storage')
    # ### end Alembic commands ###
