"""empty message

Revision ID: 21a99c2faac3
Revises: aed6dc417300
Create Date: 2020-04-08 13:13:27.043003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21a99c2faac3'
down_revision = 'aed6dc417300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('true_name', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('global_address', sa.String(length=200), nullable=True),
    sa.Column('profile_photo', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['profile_photo'], ['img_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_openid'), 'customers', ['openid'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_session_key'), 'customers', ['session_key'], unique=True)
    op.create_index(op.f('ix_customers_unionid'), 'customers', ['unionid'], unique=True)
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=True)
    op.create_table('customer_role',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'role_id')
    )
    op.add_column('login_info', sa.Column('customer', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'login_info', 'customers', ['customer'], ['id'])
    op.add_column('shop_orders', sa.Column('customer_id', sa.String(length=64), nullable=True))
    op.drop_constraint('shop_orders_ibfk_2', 'shop_orders', type_='foreignkey')
    op.create_foreign_key(None, 'shop_orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('shop_orders', 'user_id')
    op.drop_index('ix_users_wechat_id', table_name='users')
    op.drop_column('users', 'wechat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wechat_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.create_index('ix_users_wechat_id', 'users', ['wechat_id'], unique=True)
    op.add_column('shop_orders', sa.Column('user_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.create_foreign_key('shop_orders_ibfk_2', 'shop_orders', 'users', ['user_id'], ['id'])
    op.drop_column('shop_orders', 'customer_id')
    op.drop_constraint(None, 'login_info', type_='foreignkey')
    op.drop_column('login_info', 'customer')
    op.drop_table('customer_role')
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.drop_index(op.f('ix_customers_unionid'), table_name='customers')
    op.drop_index(op.f('ix_customers_session_key'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_openid'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
