"""empty message

Revision ID: 23405ea82fc4
Revises: 36bce4cb69eb
Create Date: 2020-04-25 09:13:05.293986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23405ea82fc4'
down_revision = '36bce4cb69eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('group', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'promotions', 'promotion_groups', ['group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.drop_column('promotions', 'group')
    # ### end Alembic commands ###
