"""empty message

Revision ID: 2bfcd60b0b43
Revises: f0450dbd0fb8
Create Date: 2020-07-14 22:36:32.212515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bfcd60b0b43'
down_revision = 'f0450dbd0fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_login_info', 'token')
    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=15),
               nullable=True)
    op.drop_index('ix_customers_openid', table_name='customers')
    op.create_index(op.f('ix_customers_openid'), 'customers', ['openid'], unique=True)
    op.drop_index('ix_customers_unionid', table_name='customers')
    op.create_index(op.f('ix_customers_unionid'), 'customers', ['unionid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_unionid'), table_name='customers')
    op.create_index('ix_customers_unionid', 'customers', ['unionid'], unique=False)
    op.drop_index(op.f('ix_customers_openid'), table_name='customers')
    op.create_index('ix_customers_openid', 'customers', ['openid'], unique=False)
    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=15),
               nullable=False)
    op.add_column('customer_login_info', sa.Column('token', mysql.VARCHAR(collation='utf8_bin', length=500), nullable=False))
    # ### end Alembic commands ###
