"""empty message

Revision ID: 2c54df25b052
Revises: 
Create Date: 2020-08-14 23:04:55.073541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c54df25b052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemsorders_benefits',
    sa.Column('itemsorders_id', sa.String(length=64), nullable=False),
    sa.Column('benefits_id', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['benefits_id'], ['benefits.id'], ),
    sa.ForeignKeyConstraint(['itemsorders_id'], ['items_orders.id'], ),
    sa.PrimaryKeyConstraint('itemsorders_id', 'benefits_id')
    )
    op.add_column('benefits', sa.Column('combo_express_fee', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='套餐的快递价格，例如药酒封坛，则为0'))
    op.add_column('express_address', sa.Column('recipient', sa.String(length=50), nullable=True, comment='收件人'))
    op.add_column('express_address', sa.Column('recipient_phone', sa.String(length=20), nullable=True, comment='收件人电话'))
    op.drop_column('express_address', 'recipients_phone')
    op.drop_column('express_address', 'recipients')
    op.add_column('items_orders', sa.Column('transaction_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='参与活动折扣后的价格，如果是套餐，那么显示套餐价格'))
    op.alter_column('items_orders', 'item_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='下单时sku的价格',
               existing_nullable=True)
    op.drop_column('items_orders', 'activity_discount')
    op.add_column('shop_orders', sa.Column('bank_type', sa.String(length=32), nullable=True, comment='回调用户的银行类型，如果成功'))
    op.add_column('shop_orders', sa.Column('cash_fee', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='微信支付实际现金支付金额'))
    op.add_column('shop_orders', sa.Column('customer_grade', sa.SmallInteger(), nullable=True, comment='记录订单生成时用户的级别'))
    op.add_column('shop_orders', sa.Column('customer_type', sa.SmallInteger(), nullable=True, comment='记录订单生成时用户的类型'))
    op.add_column('shop_orders', sa.Column('express_postcode', sa.String(length=7), nullable=True, comment='邮编'))
    op.add_column('shop_orders', sa.Column('express_recipient', sa.String(length=20), nullable=True, comment='收件人'))
    op.add_column('shop_orders', sa.Column('express_recipient_phone', sa.String(length=13), nullable=True, comment='收件人手机号'))
    op.add_column('shop_orders', sa.Column('pay_err_code', sa.String(length=32), nullable=True, comment='微信支付回调结果，如果有错误'))
    op.add_column('shop_orders', sa.Column('pay_err_code_des', sa.String(length=128), nullable=True, comment='微信支付回调结果描述'))
    op.add_column('shop_orders', sa.Column('pre_pay_time', sa.DateTime(), nullable=True, comment='后台支付获取预付ID成功时间'))
    op.add_column('shop_orders', sa.Column('transaction_id', sa.String(length=64), nullable=True, comment='微信支付的订单号，回调中获取'))
    op.alter_column('shop_orders', 'express_address',
               existing_type=mysql.VARCHAR(length=64),
               comment='记录下单时发货地址，防止地址记录修改。 原express_address表中address1+address2',
               existing_nullable=True)
    op.alter_column('shop_orders', 'is_pay',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='默认0. 0：未支付， 1：完成支付， 2：支付失败, 3:支付中',
               existing_comment='默认0. 0：未支付， 1：完成支付， 2：支付失败',
               existing_nullable=True)
    op.alter_column('shop_orders', 'items_total_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='未使用积分的总价',
               existing_nullable=True)
    op.alter_column('shop_orders', 'pay_time',
               existing_type=mysql.DATETIME(),
               comment='支付成功时间',
               existing_comment='支付时间',
               existing_nullable=True)
    op.drop_constraint('shop_orders_ibfk_2', 'shop_orders', type_='foreignkey')
    op.drop_column('shop_orders', 'trade_sn')
    op.add_column('sku', sa.Column('express_fee', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='sku 默认快递费'))
    op.add_column('sku', sa.Column('get_score', sa.Integer(), nullable=True, comment='可以获得的积分'))
    op.add_column('sku', sa.Column('max_score', sa.Integer(), nullable=True, comment='最多可用积分'))
    op.add_column('sku', sa.Column('need_express', sa.SmallInteger(), nullable=True, comment='1: 可快递， 0: 不可快递'))
    op.alter_column('sku', 'contents',
               existing_type=mysql.LONGTEXT(),
               comment='富文本，sku描述',
               existing_nullable=True)
    op.drop_column('sku', 'score')
    op.add_column('spu', sa.Column('delete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spu', 'delete_at')
    op.add_column('sku', sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='积分'))
    op.alter_column('sku', 'contents',
               existing_type=mysql.LONGTEXT(),
               comment=None,
               existing_comment='富文本，sku描述',
               existing_nullable=True)
    op.drop_column('sku', 'need_express')
    op.drop_column('sku', 'max_score')
    op.drop_column('sku', 'get_score')
    op.drop_column('sku', 'express_fee')
    op.add_column('shop_orders', sa.Column('trade_sn', mysql.VARCHAR(length=64), nullable=True, comment='微信支付的交易号'))
    op.create_foreign_key('shop_orders_ibfk_2', 'shop_orders', 'express_address', ['express_address'], ['id'])
    op.alter_column('shop_orders', 'pay_time',
               existing_type=mysql.DATETIME(),
               comment='支付时间',
               existing_comment='支付成功时间',
               existing_nullable=True)
    op.alter_column('shop_orders', 'items_total_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='未使用积分的总价',
               existing_nullable=True)
    op.alter_column('shop_orders', 'is_pay',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='默认0. 0：未支付， 1：完成支付， 2：支付失败',
               existing_comment='默认0. 0：未支付， 1：完成支付， 2：支付失败, 3:支付中',
               existing_nullable=True)
    op.alter_column('shop_orders', 'express_address',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='记录下单时发货地址，防止地址记录修改。 原express_address表中address1+address2',
               existing_nullable=True)
    op.drop_column('shop_orders', 'transaction_id')
    op.drop_column('shop_orders', 'pre_pay_time')
    op.drop_column('shop_orders', 'pay_err_code_des')
    op.drop_column('shop_orders', 'pay_err_code')
    op.drop_column('shop_orders', 'express_recipient_phone')
    op.drop_column('shop_orders', 'express_recipient')
    op.drop_column('shop_orders', 'express_postcode')
    op.drop_column('shop_orders', 'customer_type')
    op.drop_column('shop_orders', 'customer_grade')
    op.drop_column('shop_orders', 'cash_fee')
    op.drop_column('shop_orders', 'bank_type')
    op.add_column('items_orders', sa.Column('activity_discount', mysql.DECIMAL(precision=3, scale=2), nullable=True))
    op.alter_column('items_orders', 'item_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='下单时sku的价格',
               existing_nullable=True)
    op.drop_column('items_orders', 'transaction_price')
    op.add_column('express_address', sa.Column('recipients', mysql.VARCHAR(length=50), nullable=True, comment='收件人'))
    op.add_column('express_address', sa.Column('recipients_phone', mysql.VARCHAR(length=20), nullable=True, comment='收件人电话'))
    op.drop_column('express_address', 'recipient_phone')
    op.drop_column('express_address', 'recipient')
    op.drop_column('benefits', 'combo_express_fee')
    op.drop_table('itemsorders_benefits')
    # ### end Alembic commands ###
