"""empty message

Revision ID: 3b18fae6055e
Revises: 5233ec22e2e2
Create Date: 2020-07-25 16:16:08.604285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b18fae6055e'
down_revision = '5233ec22e2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('combo', sa.String(length=64), nullable=True, comment='前端页面选择的combo，实质为这个套餐中的一种，为benefits表的id'))
    op.add_column('shopping_cart', sa.Column('quantity', sa.SmallInteger(), nullable=True, comment='购买的数量'))
    op.create_foreign_key(None, 'shopping_cart', 'benefits', ['combo'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_cart', type_='foreignkey')
    op.drop_column('shopping_cart', 'quantity')
    op.drop_column('shopping_cart', 'combo')
    # ### end Alembic commands ###
