"""empty message

Revision ID: 3e5ac8ef9d2f
Revises: bb6fff0ad252
Create Date: 2020-05-03 17:25:51.157911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5ac8ef9d2f'
down_revision = 'bb6fff0ad252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('per_user', sa.SmallInteger(), nullable=True, comment='每用户允许领取数量'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'per_user')
    # ### end Alembic commands ###
