"""empty message

Revision ID: 3f928c3a02d5
Revises: 10ef7a5c6c72
Create Date: 2020-07-26 16:19:19.624932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f928c3a02d5'
down_revision = '10ef7a5c6c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('invitor_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'customers', 'customers', ['invitor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'invitor_id')
    # ### end Alembic commands ###
