"""empty message

Revision ID: 42c3b46130a3
Revises: 1cfc057bb8da
Create Date: 2020-07-14 14:02:41.414610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c3b46130a3'
down_revision = '1cfc057bb8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj_storage', sa.Column('url', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_obj_storage_url'), 'obj_storage', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obj_storage_url'), table_name='obj_storage')
    op.drop_column('obj_storage', 'url')
    # ### end Alembic commands ###
