"""empty message

Revision ID: 451137201082
Revises: 6b44c42edfb2
Create Date: 2020-08-02 10:23:22.998053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '451137201082'
down_revision = '6b44c42edfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rebates', sa.Column('grandinvitor_rebate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='祖父级返佣比例'))
    op.add_column('rebates', sa.Column('invitor_rebate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='父级返佣比例'))
    op.add_column('rebates', sa.Column('name', sa.String(length=64), nullable=True, comment='用来命名返佣表名称，例如‘封坛返佣’， 用来表示封坛类SKU的返佣，SKU表中外键关联此表'))
    op.add_column('rebates', sa.Column('parent_grade', sa.SmallInteger(), nullable=True, comment='1 表示上级发展来的下级，0，表示平级或者下级发展来的代理'))
    op.add_column('rebates', sa.Column('share_first_level_bonus', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='链接分享成为上下级，且成功邀请一个一级的奖金'))
    op.add_column('rebates', sa.Column('share_second_level_rebate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='链接分享成为上下级，分享者返佣比例，目前指分享成功且成为二级 5%'))
    op.drop_column('rebates', 'invitor_grade')
    op.drop_column('rebates', 'parent_rebate')
    op.drop_column('rebates', 'invite_first_level_bonus')
    op.drop_column('rebates', 'invitor_second_level_rebate')
    op.drop_column('rebates', 'grandparent_rebate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rebates', sa.Column('grandparent_rebate', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='祖父级返佣比例'))
    op.add_column('rebates', sa.Column('invitor_second_level_rebate', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='邀请者返佣比例，目前指邀请成功的二级 5%'))
    op.add_column('rebates', sa.Column('invite_first_level_bonus', mysql.DECIMAL(precision=7, scale=2), nullable=True, comment='成功邀请一个一级的奖金'))
    op.add_column('rebates', sa.Column('parent_rebate', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='父级返佣比例'))
    op.add_column('rebates', sa.Column('invitor_grade', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='1 表示上级发展来下的下级，0，表示平级或者下级发展来的代理'))
    op.drop_column('rebates', 'share_second_level_rebate')
    op.drop_column('rebates', 'share_first_level_bonus')
    op.drop_column('rebates', 'parent_grade')
    op.drop_column('rebates', 'name')
    op.drop_column('rebates', 'invitor_rebate')
    op.drop_column('rebates', 'grandinvitor_rebate')
    # ### end Alembic commands ###
