"""empty message

Revision ID: 4cc102889cfb
Revises: 3ebef750a141
Create Date: 2020-04-05 01:06:53.622001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc102889cfb'
down_revision = '3ebef750a141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_info', sa.Column('memo', sa.String(length=200), nullable=True, comment='备忘，例如作废原因'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_info', 'memo')
    # ### end Alembic commands ###
