"""empty message

Revision ID: 4cd7da09f3cd
Revises: 3e5ac8ef9d2f
Create Date: 2020-05-03 21:56:28.084391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd7da09f3cd'
down_revision = '3e5ac8ef9d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('per_user', sa.SmallInteger(), nullable=True, comment='设置限购量，默认为0不限购，一般在特价，秒杀折扣时使用'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'per_user')
    # ### end Alembic commands ###
