"""empty message

Revision ID: 5c90281ff57d
Revises: 7756a0dc6c48
Create Date: 2020-04-11 14:55:18.869411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c90281ff57d'
down_revision = '7756a0dc6c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('app_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1正常；2暂停'),
    sa.Column('callback_url', sa.String(length=100), nullable=True, comment='短信回调URL'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_app_app_id'), 'sms_app', ['app_id'], unique=False)
    op.create_index(op.f('ix_sms_app_app_key'), 'sms_app', ['app_key'], unique=False)
    op.create_table('sms_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('sign_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_template')
    op.drop_index(op.f('ix_sms_app_app_key'), table_name='sms_app')
    op.drop_index(op.f('ix_sms_app_app_id'), table_name='sms_app')
    op.drop_table('sms_app')
    # ### end Alembic commands ###
