"""empty message

Revision ID: 5dfe96bcfc4b
Revises: f0b9c78904e9
Create Date: 2020-04-03 13:22:08.327593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dfe96bcfc4b'
down_revision = 'f0b9c78904e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('img_url', 'attribute',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='1：轮播图  2：缩略图，用parent_id来关联对应的父级图  3：正文图片 4: banner图 5:logo',
               existing_comment='1：轮播图  2：缩略图，用parent_id来关联对应的父级图  3：正文图片 4: banner图',
               existing_nullable=True)
    op.drop_column('sku', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('thumbnail_url', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.alter_column('img_url', 'attribute',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='1：轮播图  2：缩略图，用parent_id来关联对应的父级图  3：正文图片 4: banner图',
               existing_comment='1：轮播图  2：缩略图，用parent_id来关联对应的父级图  3：正文图片 4: banner图 5:logo',
               existing_nullable=True)
    # ### end Alembic commands ###
