"""empty message

Revision ID: 64dfd4e3a9fc
Revises: 6066c90c1f96
Create Date: 2020-07-15 20:51:23.923839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dfd4e3a9fc'
down_revision = '6066c90c1f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj_storage', sa.Column('parent_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'obj_storage', 'obj_storage', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obj_storage', type_='foreignkey')
    op.drop_column('obj_storage', 'parent_id')
    # ### end Alembic commands ###
