"""empty message

Revision ID: 6a0f4b34f731
Revises: 2bfcd60b0b43
Create Date: 2020-07-15 08:16:15.211085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0f4b34f731'
down_revision = '2bfcd60b0b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_at')
    op.drop_column('users', 'delete_at')
    op.drop_column('users', 'create_at')
    op.drop_column('customers', 'update_at')
    op.drop_column('customers', 'delete_at')
    op.drop_column('customers', 'create_at')
    op.drop_column('customer_roles', 'permissions')
    # ### end Alembic commands ###
