"""empty message

Revision ID: 6b4cba7784e4
Revises: d391b59b6506
Create Date: 2020-07-16 07:44:39.188177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4cba7784e4'
down_revision = 'd391b59b6506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_obj',
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('obj_id', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['obj_id'], ['obj_storage.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('sku_id', 'obj_id')
    )
    op.drop_table('sku_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_img',
    sa.Column('sku_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('img_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['img_url.id'], name='sku_img_ibfk_1'),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name='sku_img_ibfk_2'),
    sa.PrimaryKeyConstraint('sku_id', 'img_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('sku_obj')
    # ### end Alembic commands ###
