"""empty message

Revision ID: 6e805ddc351d
Revises: 7ab20840e4e6
Create Date: 2020-07-19 00:14:25.533559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e805ddc351d'
down_revision = '7ab20840e4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('express_address', 'address1',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=100),
               nullable=True,
               existing_comment='某某路xx号xx栋xx门牌号')
    op.alter_column('express_address', 'recipients',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               nullable=True,
               existing_comment='收件人')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('express_address', 'recipients',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=50),
               nullable=False,
               existing_comment='收件人')
    op.alter_column('express_address', 'address1',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=100),
               nullable=False,
               existing_comment='某某路xx号xx栋xx门牌号')
    # ### end Alembic commands ###
