"""empty message

Revision ID: 6f201493448d
Revises: b8d303b24ad3
Create Date: 2020-04-06 10:03:50.583319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f201493448d'
down_revision = 'b8d303b24ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sku_layout', 'sku', ['sku_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sku_layout', type_='foreignkey')
    # ### end Alembic commands ###
