"""empty message

Revision ID: 7490f45353a2
Revises: 9b844ab9385c
Create Date: 2020-04-13 09:33:30.746619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7490f45353a2'
down_revision = '9b844ab9385c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('birthday', sa.Date(), nullable=True))
    op.alter_column('customers', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='1: 正常 0: 删除',
               existing_nullable=True)
    op.drop_index('ix_customers_email', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.drop_index('ix_customers_openid', table_name='customers')
    op.create_index(op.f('ix_customers_openid'), 'customers', ['openid'], unique=False)
    op.drop_index('ix_customers_phone', table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.drop_index('ix_customers_unionid', table_name='customers')
    op.create_index(op.f('ix_customers_unionid'), 'customers', ['unionid'], unique=False)
    op.drop_index('ix_customers_username', table_name='customers')
    op.create_index(op.f('ix_customers_username'), 'customers', ['username'], unique=False)
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    op.drop_index(op.f('ix_customers_username'), table_name='customers')
    op.create_index('ix_customers_username', 'customers', ['username'], unique=True)
    op.drop_index(op.f('ix_customers_unionid'), table_name='customers')
    op.create_index('ix_customers_unionid', 'customers', ['unionid'], unique=True)
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=True)
    op.drop_index(op.f('ix_customers_openid'), table_name='customers')
    op.create_index('ix_customers_openid', 'customers', ['openid'], unique=True)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True)
    op.alter_column('customers', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='1: 正常 0: 删除',
               existing_nullable=True)
    op.drop_column('customers', 'birthday')
    # ### end Alembic commands ###
