"""empty message

Revision ID: 7756a0dc6c48
Revises: 21a99c2faac3
Create Date: 2020-04-08 13:16:38.417429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7756a0dc6c48'
down_revision = '21a99c2faac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('express_address_ibfk_3', 'express_address', type_='foreignkey')
    op.create_foreign_key(None, 'express_address', 'customers', ['sender'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'express_address', type_='foreignkey')
    op.create_foreign_key('express_address_ibfk_3', 'express_address', 'users', ['sender'], ['id'])
    # ### end Alembic commands ###
