"""empty message

Revision ID: 775db29c683f
Revises: 6e805ddc351d
Create Date: 2020-07-20 23:44:41.139277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '775db29c683f'
down_revision = '6e805ddc351d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('express_address', 'city_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='目前不用，后续拆分地址后存放城市id',
               existing_nullable=True)
    op.alter_column('express_address', 'district',
               existing_type=mysql.INTEGER(display_width=11),
               comment='目前不用，后续拆分地址后存放区id',
               existing_nullable=True)
    op.drop_column('sku', 'home_page')
    op.drop_column('spu', 'home_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spu', sa.Column('home_page', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='0 不上首页，1 上首页'))
    op.add_column('sku', sa.Column('home_page', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='0 不上首页，1 上首页'))
    op.alter_column('express_address', 'district',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='目前不用，后续拆分地址后存放区id',
               existing_nullable=True)
    op.alter_column('express_address', 'city_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='目前不用，后续拆分地址后存放城市id',
               existing_nullable=True)
    # ### end Alembic commands ###
