"""empty message

Revision ID: 7a9526461f0e
Revises: 9e323de99f53
Create Date: 2020-07-13 15:46:55.064395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a9526461f0e'
down_revision = '9e323de99f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spu_img',
    sa.Column('spu_id', sa.String(length=64), nullable=False),
    sa.Column('img_id', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['img_id'], ['img_url.id'], ),
    sa.ForeignKeyConstraint(['spu_id'], ['spu.id'], ),
    sa.PrimaryKeyConstraint('spu_id', 'img_id')
    )
    op.drop_column('sku', 'express_fee')
    op.drop_column('sku', 'contents')
    op.add_column('spu', sa.Column('contents', sa.Text(length=4294967295), nullable=True))
    op.add_column('spu', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('spu', sa.Column('express_fee', sa.DECIMAL(precision=4, scale=2), nullable=True, comment='邮费，默认0元'))
    op.add_column('spu', sa.Column('status', sa.SmallInteger(), nullable=True, comment='1 上架； 0 下架'))
    op.add_column('spu', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spu', 'update_at')
    op.drop_column('spu', 'status')
    op.drop_column('spu', 'express_fee')
    op.drop_column('spu', 'create_at')
    op.drop_column('spu', 'contents')
    op.add_column('sku', sa.Column('contents', mysql.LONGTEXT(collation='utf8_bin'), nullable=True))
    op.add_column('sku', sa.Column('express_fee', mysql.DECIMAL(precision=4, scale=2), nullable=True, comment='邮费，默认0元'))
    op.drop_table('spu_img')
    # ### end Alembic commands ###
