"""empty message

Revision ID: 7ab20840e4e6
Revises: c4d8d1a70ab7
Create Date: 2020-07-16 09:43:44.995314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ab20840e4e6'
down_revision = 'c4d8d1a70ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brands_ibfk_1', 'brands', type_='foreignkey')
    op.create_foreign_key(None, 'brands', 'obj_storage', ['logo'], ['id'])
    op.create_foreign_key(None, 'coupons', 'obj_storage', ['icon'], ['id'])
    op.drop_constraint('customers_ibfk_1', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'obj_storage', ['profile_photo'], ['id'])
    op.drop_constraint('evaluates_ibfk_1', 'evaluates', type_='foreignkey')
    op.create_foreign_key(None, 'evaluates', 'obj_storage', ['used_pic'], ['id'])
    op.drop_table('img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluates', type_='foreignkey')
    op.create_foreign_key('evaluates_ibfk_1', 'evaluates', 'img_url', ['used_pic'], ['id'])
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_ibfk_1', 'customers', 'img_url', ['profile_photo'], ['id'])
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.create_foreign_key('coupons_ibfk_1', 'coupons', 'img_url', ['icon'], ['id'])
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.create_foreign_key('brands_ibfk_1', 'brands', 'img_url', ['logo'], ['id'])
    op.create_table('img_url',
    sa.Column('id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('path', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=False),
    sa.Column('attribute', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='1：轮播图  2：缩略图，用parent_id来关联对应的父级图  3：正文图片 4: banner图 5:logo'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_img_url_path', 'img_url', ['path'], unique=True)
    op.create_index('ix_img_url_attribute', 'img_url', ['attribute'], unique=False)
    # ### end Alembic commands ###
