"""empty message

Revision ID: 826ea9f271cd
Revises: 90b04b7c5605
Create Date: 2020-04-29 10:06:16.743041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '826ea9f271cd'
down_revision = '90b04b7c5605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefits', 'express_free')
    op.add_column('promotions', sa.Column('express_free', sa.SmallInteger(), nullable=True, comment='0: 不包邮, 1: 包邮'))
    op.alter_column('promotions', 'gender',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='参与的性别，默认为0， 1为男性、2为女性',
               existing_comment='参与的性别，默认为0',
               existing_nullable=True)
    op.alter_column('promotions', 'with_special',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='1: 可用于特价商品 0: 不能。默认不能(商品优惠卷除外)',
               existing_comment='1: 可用于特价商品 2: 不能。默认不能(商品优惠卷除外)',
               existing_nullable=True)
    op.drop_column('promotions', 'used_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('used_in', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False, comment="可用于：10店铺优惠券 11新人店铺券  20商品优惠券  30类目优惠券  60平台优惠券 61新人平台券'"))
    op.alter_column('promotions', 'with_special',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='1: 可用于特价商品 2: 不能。默认不能(商品优惠卷除外)',
               existing_comment='1: 可用于特价商品 0: 不能。默认不能(商品优惠卷除外)',
               existing_nullable=True)
    op.alter_column('promotions', 'gender',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='参与的性别，默认为0',
               existing_comment='参与的性别，默认为0， 1为男性、2为女性',
               existing_nullable=True)
    op.drop_column('promotions', 'express_free')
    op.add_column('benefits', sa.Column('express_free', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='0: 不包邮, 1: 包邮'))
    # ### end Alembic commands ###
