"""empty message

Revision ID: 839bcd66453c
Revises: 52fa38561abf
Create Date: 2020-04-04 12:35:25.334483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '839bcd66453c'
down_revision = '52fa38561abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sku', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1 上架； 0 下架',
               existing_comment='True 上架； False 下架',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sku', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='True 上架； False 下架',
               existing_comment='1 上架； 0 下架',
               existing_nullable=True)
    # ### end Alembic commands ###
