"""empty message

Revision ID: 8a29d205351e
Revises: 454098bbb729
Create Date: 2020-08-26 22:23:17.235405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a29d205351e'
down_revision = '454098bbb729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_center', sa.Column('news_section_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'news_center', 'news_sections', ['news_section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_center', type_='foreignkey')
    op.drop_column('news_center', 'news_section_id')
    # ### end Alembic commands ###
