"""empty message

Revision ID: 8c703fc0b7ad
Revises: b8996cce44ae
Create Date: 2020-04-06 00:09:11.850013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c703fc0b7ad'
down_revision = 'b8996cce44ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='页面板块名称'),
    sa.Column('desc', sa.String(length=100), nullable=True, comment='描述、备注'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_sku',
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1 正常，0 禁用'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('sku_id', 'layout_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layout_sku')
    op.drop_table('layout')
    # ### end Alembic commands ###
