"""empty message

Revision ID: 90b04b7c5605
Revises: baf8e5bed0a2
Create Date: 2020-04-26 19:46:47.780389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90b04b7c5605'
down_revision = 'baf8e5bed0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotions', 'first_order',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0: 不是首单，1: 首单, 用户首单参加活动',
               existing_comment='0: 不是首单，1: 是首单',
               existing_nullable=True)
    op.create_index(op.f('ix_promotions_name'), 'promotions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotions_name'), table_name='promotions')
    op.alter_column('promotions', 'first_order',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0: 不是首单，1: 是首单',
               existing_comment='0: 不是首单，1: 首单, 用户首单参加活动',
               existing_nullable=True)
    # ### end Alembic commands ###
