"""empty message

Revision ID: 9a221a853870
Revises: f62addb702d0
Create Date: 2020-08-29 13:44:15.826969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a221a853870'
down_revision = 'f62addb702d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('total_cargoes', sa.Column('storage_date', sa.DateTime(), nullable=True))
    op.drop_column('total_cargoes', 'seal_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('total_cargoes', sa.Column('seal_date', mysql.DATETIME(), nullable=True))
    op.drop_column('total_cargoes', 'storage_date')
    # ### end Alembic commands ###
