"""empty message

Revision ID: 9e323de99f53
Revises: ece3d93a9753
Create Date: 2020-07-12 17:29:43.784208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e323de99f53'
down_revision = 'ece3d93a9753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('express_fee', sa.DECIMAL(precision=4, scale=2), nullable=True, comment='邮费，默认0元'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'express_fee')
    # ### end Alembic commands ###
