"""empty message

Revision ID: 9f854d4a8543
Revises: 
Create Date: 2020-04-02 22:17:23.293763

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9f854d4a8543'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail_url',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('path', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_thumbnail_url_path'), 'thumbnail_url', ['path'], unique=True)
    op.create_table('img_url',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('path', sa.String(length=100), nullable=False),
                    sa.Column('attribute', sa.SmallInteger(), nullable=True,
                              comment='1：轮播图  2：缩略图，用parent_id来关联对应的父级图  3：正文图片 4: banner图'),
                    sa.Column('thumbnail_id', sa.String(length=64), nullable=True),
                    sa.ForeignKeyConstraint(['thumbnail_id'], ['thumbnail_url.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_img_url_attribute'), 'img_url', ['attribute'], unique=False)
    op.create_index(op.f('ix_img_url_path'), 'img_url', ['path'], unique=True)
    op.create_table('brands',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)

    op.create_table('countries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('longitude', sa.String(length=20), nullable=True),
                    sa.Column('latitude', sa.String(length=20), nullable=True),
                    sa.Column('population', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)

    op.create_table('provinces',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('longitude', sa.String(length=20), nullable=True),
                    sa.Column('latitude', sa.String(length=20), nullable=True),
                    sa.Column('population', sa.Integer(), nullable=True),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_provinces_name'), 'provinces', ['name'], unique=True)

    op.create_table('cities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('longitude', sa.String(length=20), nullable=True),
                    sa.Column('latitude', sa.String(length=20), nullable=True),
                    sa.Column('population', sa.Integer(), nullable=True),
                    sa.Column('province_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)

    op.create_table('districts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('longitude', sa.String(length=20), nullable=True),
                    sa.Column('latitude', sa.String(length=20), nullable=True),
                    sa.Column('population', sa.Integer(), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)

    op.create_table('classifies',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('coupons',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False, comment='优惠券标题'),
                    sa.Column('icon', sa.String(length=64), nullable=True, comment='优惠券图标'),
                    sa.Column('used_in', sa.SmallInteger(), nullable=False,
                              comment="可用于：10店铺优惠券 11新人店铺券  20商品优惠券  30类目优惠券  60平台优惠券 61新人平台券'"),
                    sa.Column('coupon_type', sa.SmallInteger(), nullable=True, comment='1满减券 2叠加满减券 3无门槛券（需要限制大小）'),
                    sa.Column('with_special', sa.SmallInteger(), nullable=True, comment='1可用于特价商品 2不能  默认不能(商品优惠卷除外)'),
                    sa.Column('with_sn', sa.String(length=64), nullable=True, comment='SPU或SKU ID'),
                    sa.Column('with_amount', sa.Integer(), nullable=True, comment='满多少金额'),
                    sa.Column('used_amount', sa.Integer(), nullable=True, comment='用券金额'),
                    sa.Column('quota', sa.Integer(), nullable=True, comment='配额：发券数量'),
                    sa.Column('take_count', sa.Integer(), nullable=True, comment='已领取的优惠券数量'),
                    sa.Column('used_count', sa.Integer(), nullable=True, comment='已使用的优惠券数量'),
                    sa.Column('start_time', sa.DateTime(), nullable=True, comment='发放开始时间'),
                    sa.Column('end_time', sa.DateTime(), nullable=True, comment='发放结束时间'),
                    sa.Column('valid_type', sa.SmallInteger(), nullable=True,
                              comment='时效:1绝对时效（领取后XXX-XXX时间段有效）  2相对时效（领取后N天有效）'),
                    sa.Column('valid_days', sa.Integer(), nullable=True, comment='自领取之日起有效天数'),
                    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1生效 2失效 3已结束'),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.Column('update_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['icon'], ['img_url.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('coupon_ready',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('coupon_id', sa.String(length=64), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True, comment='0: 作废，1：已领取未使用，2：已使用'),
                    sa.Column('take_at', sa.DateTime(), nullable=True),
                    sa.Column('use_at', sa.DateTime(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('evaluates',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('order', sa.String(length=64), nullable=True),
                    sa.Column('express_rate', sa.SmallInteger(), nullable=True, comment='物流评价0~10'),
                    sa.Column('item_rate', sa.SmallInteger(), nullable=True, comment='商品评价0~10'),
                    sa.Column('content', sa.Text(length=4294967295), nullable=True),
                    sa.Column('used_pic', sa.String(length=64), nullable=True),
                    sa.ForeignKeyConstraint(['used_pic'], ['img_url.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('spu',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('sub_name', sa.String(length=100), nullable=True),
                    sa.Column('brand_id', sa.String(length=64), nullable=True),
                    sa.Column('classify_id', sa.String(length=64), nullable=True),
                    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
                    sa.ForeignKeyConstraint(['classify_id'], ['classifies.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_spu_name'), 'spu', ['name'], unique=False)

    op.create_table('sku',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=7, scale=2), nullable=True),
                    sa.Column('discount', sa.DECIMAL(precision=3, scale=2), nullable=True),
                    sa.Column('member_price', sa.DECIMAL(precision=7, scale=2), nullable=True),
                    sa.Column('score_types', sa.Boolean(), nullable=True),
                    sa.Column('contents', sa.Text(length=4294967295), nullable=True),
                    sa.Column('thumbnail_url', sa.String(length=100), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('spu_id', sa.String(length=64), nullable=True),
                    sa.Column('status', sa.Boolean(), nullable=True, comment='True 上架； False 下架'),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.Column('update_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['spu_id'], ['spu.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_sku_name'), 'sku', ['name'], unique=False)
    op.create_index(op.f('ix_sku_quantity'), 'sku', ['quantity'], unique=False)
    op.create_table('permissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('action', sa.String(length=250), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=True)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)

    op.create_table('menu',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('icon', sa.String(length=50), nullable=True),
                    sa.Column('url', sa.String(length=250), nullable=True),
                    sa.Column('order', sa.SmallInteger(), nullable=True),
                    sa.Column('bg_color', sa.String(length=50), nullable=True),
                    sa.Column('type', sa.String(length=20), nullable=True),
                    sa.Column('permission', sa.Integer(), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ),
                    sa.ForeignKeyConstraint(['permission'], ['permissions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('options_dic',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('key', sa.String(length=80), nullable=False),
                    sa.Column('label', sa.String(length=20), nullable=False),
                    sa.Column('value', sa.String(length=5), nullable=False),
                    sa.Column('order', sa.SmallInteger(), nullable=True),
                    sa.Column('status', sa.Boolean(), nullable=True),
                    sa.Column('selected', sa.Boolean(), nullable=True),
                    sa.Column('type', sa.String(length=20), nullable=True),
                    sa.Column('memo', sa.String(length=100), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key', 'label', name='_key_label_combine')
                    )
    op.create_index(op.f('ix_options_dic_key'), 'options_dic', ['key'], unique=False)
    op.create_index(op.f('ix_options_dic_label'), 'options_dic', ['label'], unique=False)
    op.create_index(op.f('ix_options_dic_name'), 'options_dic', ['name'], unique=False)
    op.create_index(op.f('ix_options_dic_value'), 'options_dic', ['value'], unique=False)

    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)


    op.create_table('standards',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_standards_name'), 'standards', ['name'], unique=True)


    op.create_table('users',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('email', sa.String(length=64), nullable=True),
                    sa.Column('phone', sa.String(length=15), nullable=True),
                    sa.Column('wechat_id', sa.String(length=50), nullable=True),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('true_name', sa.String(length=30), nullable=True),
                    sa.Column('gender', sa.SmallInteger(), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('global_address', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_wechat_id'), 'users', ['wechat_id'], unique=True)

    op.create_table('login_info',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=500), nullable=False),
                    sa.Column('login_time', sa.Integer(), nullable=False),
                    sa.Column('platform', sa.String(length=20), nullable=False),
                    sa.Column('login_ip', sa.String(length=64), nullable=True),
                    sa.Column('user', sa.String(length=64), nullable=True),
                    sa.Column('status', sa.Boolean(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('express_address',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('sender', sa.String(length=64), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.Column('district', sa.Integer(), nullable=True),
                    sa.Column('address1', sa.String(length=100), nullable=False, comment='某某路xx号xx栋xx门牌号'),
                    sa.Column('address2', sa.String(length=100), nullable=True),
                    sa.Column('postcode', sa.String(length=10), nullable=True, comment='邮编'),
                    sa.Column('recipients', sa.String(length=50), nullable=False, comment='收件人'),
                    sa.Column('recipients_phone', sa.String(length=20), nullable=True, comment='收件人电话'),
                    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1：正常 0：删除'),
                    sa.Column('is_default', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.ForeignKeyConstraint(['district'], ['districts.id'], ),
                    sa.ForeignKeyConstraint(['sender'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('shop_orders',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('user_id', sa.String(length=64), nullable=True),
                    sa.Column('trade_sn', sa.String(length=64), nullable=True, comment='微信支付的交易号'),
                    sa.Column('items_total_price', sa.DECIMAL(precision=9, scale=2), nullable=True),
                    sa.Column('score_used', sa.Integer(), nullable=True, comment='使用的积分'),
                    sa.Column('is_pay', sa.SmallInteger(), nullable=True, comment='默认0. 0：未支付， 1：完成支付， 2：支付失败'),
                    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='支付时间'),
                    sa.Column('is_ship', sa.SmallInteger(), nullable=True, comment='0：未发货，1：已发货'),
                    sa.Column('ship_time', sa.DateTime(), nullable=True, comment='发货时间'),
                    sa.Column('receive_time', sa.DateTime(), nullable=True, comment='收货时间'),
                    sa.Column('is_receipt', sa.SmallInteger(), nullable=True, comment='0：未发货 1：已发货未签收 2：已发货已签收'),
                    sa.Column('express_company', sa.String(length=50), nullable=True),
                    sa.Column('express_number', sa.String(length=50), nullable=True),
                    sa.Column('express_fee', sa.DECIMAL(precision=7, scale=2), nullable=True),
                    sa.Column('express_address', sa.String(length=64), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1：正常 2：禁用 0：订单取消'),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.Column('update_at', sa.DateTime(), nullable=True),
                    sa.Column('message', sa.String(length=500), nullable=True, comment='用户留言'),
                    sa.ForeignKeyConstraint(['express_address'], ['express_address.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('items_orders',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('order_id', sa.String(length=64), nullable=True),
                    sa.Column('item_id', sa.String(length=64), nullable=True),
                    sa.Column('item_quantity', sa.Integer(), nullable=True),
                    sa.Column('item_price', sa.DECIMAL(precision=7, scale=2), nullable=True),
                    sa.Column('activity_discount', sa.DECIMAL(precision=3, scale=2), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.Column('update_at', sa.DateTime(), nullable=True),
                    sa.Column('rates', sa.String(length=64), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['sku.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['shop_orders.id'], ),
                    sa.ForeignKeyConstraint(['rates'], ['evaluates.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('standard_value',
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.Column('standard_id', sa.String(length=64), nullable=True),
                    sa.Column('value', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_standard_value_value'), 'standard_value', ['value'], unique=True)

    op.create_table('role_menu',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('menu_id', sa.Integer(), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('role_id', 'menu_id')
                    )

    op.create_table('sku_img',
                    sa.Column('sku_id', sa.String(length=64), nullable=False),
                    sa.Column('img_id', sa.String(length=64), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['img_id'], ['img_url.id'], ),
                    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
                    sa.PrimaryKeyConstraint('sku_id', 'img_id')
                    )
    op.create_table('sku_shoporders',
                    sa.Column('sku_id', sa.String(length=64), nullable=False),
                    sa.Column('shoporders_id', sa.String(length=64), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['shoporders_id'], ['shop_orders.id'], ),
                    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
                    sa.PrimaryKeyConstraint('sku_id', 'shoporders_id')
                    )
    op.create_table('sku_standardvalue',
                    sa.Column('sku_id', sa.String(length=64), nullable=False),
                    sa.Column('standardvalue_id', sa.String(length=64), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
                    sa.ForeignKeyConstraint(['standardvalue_id'], ['standard_value.id'], ),
                    sa.PrimaryKeyConstraint('sku_id', 'standardvalue_id')
                    )

    op.create_table('spu_standards',
                    sa.Column('spu_id', sa.String(length=64), nullable=False),
                    sa.Column('standards_id', sa.String(length=64), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['spu_id'], ['spu.id'], ),
                    sa.ForeignKeyConstraint(['standards_id'], ['standards.id'], ),
                    sa.PrimaryKeyConstraint('spu_id', 'standards_id')
                    )


    op.create_table('user_role',
                    sa.Column('user_id', sa.String(length=64), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('create_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'role_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wechat_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_thumbnail_url_path'), table_name='thumbnail_url')
    op.drop_table('thumbnail_url')
    op.drop_index(op.f('ix_standards_name'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_standard_value_value'), table_name='standard_value')
    op.drop_table('standard_value')
    op.drop_table('spu_standards')
    op.drop_index(op.f('ix_spu_name'), table_name='spu')
    op.drop_table('spu')
    op.drop_table('sku_standardvalue')
    op.drop_table('sku_shoporders')
    op.drop_table('sku_img')
    op.drop_index(op.f('ix_sku_quantity'), table_name='sku')
    op.drop_index(op.f('ix_sku_name'), table_name='sku')
    op.drop_table('sku')
    op.drop_table('shop_orders')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('role_menu')
    op.drop_index(op.f('ix_provinces_name'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_options_dic_value'), table_name='options_dic')
    op.drop_index(op.f('ix_options_dic_name'), table_name='options_dic')
    op.drop_index(op.f('ix_options_dic_label'), table_name='options_dic')
    op.drop_index(op.f('ix_options_dic_key'), table_name='options_dic')
    op.drop_table('options_dic')
    op.drop_table('menu')
    op.drop_table('login_info')
    op.drop_table('items_orders')
    op.drop_index(op.f('ix_img_url_path'), table_name='img_url')
    op.drop_index(op.f('ix_img_url_attribute'), table_name='img_url')
    op.drop_table('img_url')
    op.drop_table('express_address')
    op.drop_table('evaluates')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('coupons')
    op.drop_table('coupon_ready')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('classifies')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
