"""empty message

Revision ID: aed6dc417300
Revises: 6f201493448d
Create Date: 2020-04-06 10:47:11.685957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aed6dc417300'
down_revision = '6f201493448d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku_layout', sa.Column('layout_id', sa.Integer(), nullable=True))
    op.drop_constraint('sku_layout_ibfk_1', 'sku_layout', type_='foreignkey')
    op.create_foreign_key(None, 'sku_layout', 'layout', ['layout_id'], ['id'])
    op.drop_column('sku_layout', 'layout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku_layout', sa.Column('layout', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sku_layout', type_='foreignkey')
    op.create_foreign_key('sku_layout_ibfk_1', 'sku_layout', 'layout', ['layout'], ['id'])
    op.drop_column('sku_layout', 'layout_id')
    # ### end Alembic commands ###
