"""empty message

Revision ID: b55a774f1084
Revises: d072666ff3f2
Create Date: 2020-04-12 08:56:39.889195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55a774f1084'
down_revision = 'd072666ff3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sku', sa.Column('special', sa.SmallInteger(), nullable=True, comment='0 非特价商品，1 特价商品'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'special')
    # ### end Alembic commands ###
