"""empty message

Revision ID: b8996cce44ae
Revises: 4cc102889cfb
Create Date: 2020-04-05 01:19:01.935981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8996cce44ae'
down_revision = '4cc102889cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_info', 'unit')
    op.add_column('sku', sa.Column('unit', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'unit')
    op.add_column('purchase_info', sa.Column('unit', mysql.VARCHAR(collation='utf8_bin', length=6), nullable=False))
    # ### end Alembic commands ###
