"""empty message

Revision ID: b8d303b24ad3
Revises: 8c703fc0b7ad
Create Date: 2020-04-06 09:27:35.713026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8d303b24ad3'
down_revision = '8c703fc0b7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_layout',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('layout', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='0 禁用 1 正常'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['layout'], ['layout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('layout_sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout_sku',
    sa.Column('sku_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='1 正常，0 禁用'),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], name='layout_sku_ibfk_1'),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name='layout_sku_ibfk_2'),
    sa.PrimaryKeyConstraint('sku_id', 'layout_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('sku_layout')
    # ### end Alembic commands ###
