"""empty message

Revision ID: bb6fff0ad252
Revises: 0fff0cb1d2ac
Create Date: 2020-04-30 15:20:30.861867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb6fff0ad252'
down_revision = '0fff0cb1d2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('desc', sa.String(length=100), nullable=True, comment='优惠券描述'))
    op.alter_column('coupons', 'absolute_date',
               existing_type=mysql.DATETIME(),
               comment='优惠券的绝对结束日期，当valid_type为1时，此项不能为空',
               existing_comment='当valid_type为1时，此项不能为空',
               existing_nullable=True)
    op.drop_column('coupons', 'start_time')
    op.drop_column('coupons', 'used_in')
    op.drop_column('coupons', 'with_amount')
    op.drop_column('coupons', 'with_sn')
    op.drop_column('coupons', 'with_special')
    op.drop_column('coupons', 'used_amount')
    op.drop_column('coupons', 'coupon_type')
    op.drop_column('coupons', 'end_time')
    op.add_column('promotions', sa.Column('coupon_id', sa.String(length=64), nullable=True))
    op.alter_column('promotions', 'group',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment='group_id 为-1表示是发优惠券，>=0的group，为活动',
               existing_nullable=True)
    op.alter_column('promotions', 'promotion_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0: 满减，1：满赠，2：满折，3：加价购，4：套餐，5：预售, 6：秒杀, 7: 满减优惠券, 8: 满赠优惠券',
               existing_comment='0: 满减，1：满赠，2：满折，3：加价购，4：套餐，5：预售, 6：秒杀',
               existing_nullable=True)
    op.create_foreign_key(None, 'promotions', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.alter_column('promotions', 'promotion_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0: 满减，1：满赠，2：满折，3：加价购，4：套餐，5：预售, 6：秒杀',
               existing_comment='0: 满减，1：满赠，2：满折，3：加价购，4：套餐，5：预售, 6：秒杀, 7: 满减优惠券, 8: 满赠优惠券',
               existing_nullable=True)
    op.alter_column('promotions', 'group',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               comment=None,
               existing_comment='group_id 为-1表示是发优惠券，>=0的group，为活动',
               existing_nullable=True)
    op.drop_column('promotions', 'coupon_id')
    op.add_column('coupons', sa.Column('end_time', mysql.DATETIME(), nullable=True, comment='发放结束时间'))
    op.add_column('coupons', sa.Column('coupon_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='1满减券 2叠加满减券 3无门槛券（需要限制大小）'))
    op.add_column('coupons', sa.Column('used_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用券金额'))
    op.add_column('coupons', sa.Column('with_special', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='1可用于特价商品 2不能  默认不能(商品优惠卷除外)'))
    op.add_column('coupons', sa.Column('with_sn', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True, comment='SPU或SKU ID'))
    op.add_column('coupons', sa.Column('with_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='满多少金额'))
    op.add_column('coupons', sa.Column('used_in', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False, comment="可用于：10店铺优惠券 11新人店铺券  20商品优惠券  30类目优惠券  60平台优惠券 61新人平台券'"))
    op.add_column('coupons', sa.Column('start_time', mysql.DATETIME(), nullable=True, comment='发放开始时间'))
    op.alter_column('coupons', 'absolute_date',
               existing_type=mysql.DATETIME(),
               comment='当valid_type为1时，此项不能为空',
               existing_comment='优惠券的绝对结束日期，当valid_type为1时，此项不能为空',
               existing_nullable=True)
    op.drop_column('coupons', 'desc')
    # ### end Alembic commands ###
