"""empty message

Revision ID: c04bc30a7663
Revises: b55a774f1084
Create Date: 2020-04-12 10:32:37.502790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04bc30a7663'
down_revision = 'b55a774f1084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('absolute_date', sa.DateTime(), nullable=True, comment='当valid_type为1时，此项不能为空'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'absolute_date')
    # ### end Alembic commands ###
