"""empty message

Revision ID: c4d8d1a70ab7
Revises: 6b4cba7784e4
Create Date: 2020-07-16 09:13:24.259271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d8d1a70ab7'
down_revision = '6b4cba7784e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spu', sa.Column('home_page', sa.SmallInteger(), nullable=True, comment='0 不上首页，1 上首页'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spu', 'home_page')
    # ### end Alembic commands ###
