"""empty message

Revision ID: c8b28ba8b8ea
Revises: 1b34965fa668
Create Date: 2020-08-11 18:54:55.296116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8b28ba8b8ea'
down_revision = '1b34965fa668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('express_address_record', sa.String(length=200), nullable=True, comment='记录下单时发货地址，防止地址记录修改'))
    op.drop_constraint('shop_orders_ibfk_1', 'shop_orders', type_='foreignkey')
    op.drop_column('shop_orders', 'express_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_orders', sa.Column('express_address', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.create_foreign_key('shop_orders_ibfk_1', 'shop_orders', 'express_address', ['express_address'], ['id'])
    op.drop_column('shop_orders', 'express_address_record')
    # ### end Alembic commands ###
