"""empty message

Revision ID: d072666ff3f2
Revises: d9ebd79d23b0
Create Date: 2020-04-11 19:27:30.283524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd072666ff3f2'
down_revision = 'd9ebd79d23b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_app', sa.Column('platform', sa.String(length=100), nullable=False))
    op.add_column('sms_template', sa.Column('platform', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_template', 'platform')
    op.drop_column('sms_app', 'platform')
    # ### end Alembic commands ###
