"""empty message

Revision ID: d277a710ae31
Revises: 13c4d77c0730
Create Date: 2020-07-15 10:39:18.212262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd277a710ae31'
down_revision = '13c4d77c0730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_login_info')
    op.add_column('login_info', sa.Column('customer', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'login_info', 'customers', ['customer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_info', type_='foreignkey')
    op.drop_column('login_info', 'customer')
    op.create_table('customer_login_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('session_key', mysql.VARCHAR(collation='utf8_bin', length=500), nullable=False),
    sa.Column('login_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('login_ip', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('customer', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.Column('update_at', mysql.DATETIME(), nullable=True),
    sa.Column('delete_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], name='customer_login_info_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
