"""empty message

Revision ID: d841da0ab3c1
Revises: 3b18fae6055e
Create Date: 2020-07-25 16:24:29.457706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd841da0ab3c1'
down_revision = '3b18fae6055e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('shopping_cart', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('shopping_cart', sa.Column('status', sa.SmallInteger(), nullable=True, comment='预留，默认为1，则显示在购物车中，如果为0， 则作为想买货物，不在购物车内'))
    op.add_column('shopping_cart', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'update_at')
    op.drop_column('shopping_cart', 'status')
    op.drop_column('shopping_cart', 'delete_at')
    op.drop_column('shopping_cart', 'create_at')
    # ### end Alembic commands ###
