"""empty message

Revision ID: dcfca7d4f6df
Revises: 
Create Date: 2020-08-14 23:07:33.205245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcfca7d4f6df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_orders', 'transaction_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='参与活动折扣后的价格，如果是套餐，那么显示套餐价格',
               existing_comment='参与活动折扣后的价格，如果是套餐，那么现实套餐价格',
               existing_nullable=True)
    op.add_column('shop_orders', sa.Column('customer_grade', sa.SmallInteger(), nullable=True, comment='记录订单生成时用户的级别'))
    op.add_column('shop_orders', sa.Column('customer_type', sa.SmallInteger(), nullable=True, comment='记录订单生成时用户的类型'))
    op.add_column('shop_orders', sa.Column('pre_pay_time', sa.DateTime(), nullable=True, comment='后台支付获取预付ID成功时间'))
    op.alter_column('shop_orders', 'is_pay',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='默认0. 0：未支付， 1：完成支付， 2：支付失败, 3:支付中',
               existing_comment='默认0. 0：未支付， 1：完成支付， 2：支付失败',
               existing_nullable=True)
    op.alter_column('shop_orders', 'pay_time',
               existing_type=mysql.DATETIME(),
               comment='支付成功时间',
               existing_comment='支付时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_orders', 'pay_time',
               existing_type=mysql.DATETIME(),
               comment='支付时间',
               existing_comment='支付成功时间',
               existing_nullable=True)
    op.alter_column('shop_orders', 'is_pay',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='默认0. 0：未支付， 1：完成支付， 2：支付失败',
               existing_comment='默认0. 0：未支付， 1：完成支付， 2：支付失败, 3:支付中',
               existing_nullable=True)
    op.drop_column('shop_orders', 'pre_pay_time')
    op.drop_column('shop_orders', 'customer_type')
    op.drop_column('shop_orders', 'customer_grade')
    op.alter_column('items_orders', 'transaction_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='参与活动折扣后的价格，如果是套餐，那么现实套餐价格',
               existing_comment='参与活动折扣后的价格，如果是套餐，那么显示套餐价格',
               existing_nullable=True)
    # ### end Alembic commands ###
