"""empty message

Revision ID: dfbc3ddd2679
Revises: 676badbadf54
Create Date: 2020-04-16 00:46:39.436844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfbc3ddd2679'
down_revision = '676badbadf54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_recharge_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('recharge_amount', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='充值金额'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('card_no', sa.String(length=50), nullable=False, comment='会员卡号'),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='会员卡状态 0: 禁用， 1：正常, 2：挂失'),
    sa.Column('grade', sa.SmallInteger(), nullable=True, comment='会员卡等级，在OptionsDict表中查找card_grades来获取对应的文字描述.默认为1'),
    sa.Column('discount', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='会员折扣'),
    sa.Column('shop_id', sa.String(length=64), nullable=True, comment='预留，对于店铺发店铺会员卡，目前会员卡为商城全局'),
    sa.Column('open_date', sa.DateTime(), nullable=True, comment='开卡日期'),
    sa.Column('validate_date', sa.DateTime(), nullable=True, comment='卡有效期'),
    sa.Column('note', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('creator_id', sa.String(length=64), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='如果不为空，则表示软删除'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.SmallInteger(), nullable=True, comment='1: 订单, 提在字典表中，查询point_records获取'),
    sa.Column('source_id', sa.String(length=64), nullable=True, comment='积分源ID'),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=True, comment='1: 增长， 2: 消费，3: 罚扣'),
    sa.Column('points', sa.Integer(), nullable=True, comment='积分数'),
    sa.Column('note', sa.String(length=100), nullable=True, comment='预留给客服做备注'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['member_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('level', sa.SmallInteger(), nullable=True, comment='用户等级'))
    op.add_column('customers', sa.Column('total_consumption', sa.DECIMAL(precision=7, scale=2), nullable=True, comment='累积消费'))
    op.add_column('customers', sa.Column('total_count', sa.Integer(), nullable=True, comment='累积消费次数'))
    op.add_column('customers', sa.Column('total_points', sa.Integer(), nullable=True, comment='用户积分'))
    op.alter_column('sku', 'score_types',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否可用积分',
               existing_nullable=True)
    op.alter_column('sku', 'special',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0 非特价商品，1 特价商品， 2 赠品，不可单独销售',
               existing_comment='0 非特价商品，1 特价商品',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sku', 'special',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='0 非特价商品，1 特价商品',
               existing_comment='0 非特价商品，1 特价商品， 2 赠品，不可单独销售',
               existing_nullable=True)
    op.alter_column('sku', 'score_types',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否可用积分',
               existing_nullable=True)
    op.drop_column('customers', 'total_points')
    op.drop_column('customers', 'total_count')
    op.drop_column('customers', 'total_consumption')
    op.drop_column('customers', 'level')
    op.drop_table('point_records')
    op.drop_table('member_cards')
    op.drop_table('member_recharge_records')
    # ### end Alembic commands ###
