"""empty message

Revision ID: ece3d93a9753
Revises: 4cd7da09f3cd
Create Date: 2020-06-18 11:02:51.306193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ece3d93a9753'
down_revision = '4cd7da09f3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotion_groups', 'priority',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='优先级不可重复，用于排序',
               existing_comment='1-10, 10优先级最低，当有组互斥时，使用优先级最高的，0优先级最高',
               existing_nullable=True)
    op.create_unique_constraint(None, 'promotion_groups', ['priority'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotion_groups', type_='unique')
    op.alter_column('promotion_groups', 'priority',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='1-10, 10优先级最低，当有组互斥时，使用优先级最高的，0优先级最高',
               existing_comment='优先级不可重复，用于排序',
               existing_nullable=True)
    op.drop_column('member_cards', 'member_type')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'parent_id')
    # ### end Alembic commands ###
