"""empty message

Revision ID: f0450dbd0fb8
Revises: 42c3b46130a3
Create Date: 2020-07-14 22:03:05.723090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0450dbd0fb8'
down_revision = '42c3b46130a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password_hash')
    op.add_column('login_info', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('login_info', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_constraint('login_info_ibfk_2', 'login_info', type_='foreignkey')
    op.drop_column('login_info', 'customer')
    op.drop_column('obj_storage', 'delete_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj_storage', sa.Column('delete_at', mysql.DATETIME(), nullable=True))
    op.add_column('login_info', sa.Column('customer', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.create_foreign_key('login_info_ibfk_2', 'login_info', 'customers', ['customer'], ['id'])
    op.drop_column('login_info', 'update_at')
    op.drop_column('login_info', 'delete_at')
    op.add_column('customers', sa.Column('password_hash', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'role_id')
    op.add_column('banners', sa.Column('delete_at', mysql.DATETIME(), nullable=True))
    op.drop_table('customer_login_info')
    op.drop_index(op.f('ix_customer_roles_default'), table_name='customer_roles')
    op.drop_table('customer_roles')
    # ### end Alembic commands ###
