"""empty message

Revision ID: f0b9c78904e9
Revises: 9f854d4a8543
Create Date: 2020-04-03 08:09:07.125307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0b9c78904e9'
down_revision = '9f854d4a8543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('company_address', sa.String(length=100), nullable=True))
    op.add_column('brands', sa.Column('company_name', sa.String(length=100), nullable=True))
    op.add_column('brands', sa.Column('logo', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'brands', 'img_url', ['logo'], ['id'])
    op.drop_column('evaluates', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluates', sa.Column('order', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_column('brands', 'logo')
    op.drop_column('brands', 'company_name')
    op.drop_column('brands', 'company_address')
    # ### end Alembic commands ###
