"""empty message

Revision ID: f4969ecad31b
Revises: d277a710ae31
Create Date: 2020-07-15 20:48:38.533773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4969ecad31b'
down_revision = 'd277a710ae31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('img_url_ibfk_1', 'img_url', type_='foreignkey')
    op.drop_column('img_url', 'thumbnail_id')
    op.add_column('obj_storage', sa.Column('thumbnail_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'obj_storage', 'thumbnail_url', ['thumbnail_id'], ['id'])
    op.add_column('sku', sa.Column('home_page', sa.SmallInteger(), nullable=True, comment='0 不上首页，1 上首页'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sku', 'home_page')
    op.drop_constraint(None, 'obj_storage', type_='foreignkey')
    op.drop_column('obj_storage', 'thumbnail_id')
    op.add_column('img_url', sa.Column('thumbnail_id', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True))
    op.create_foreign_key('img_url_ibfk_1', 'img_url', 'thumbnail_url', ['thumbnail_id'], ['id'])
    # ### end Alembic commands ###
