"""empty message

Revision ID: f62addb702d0
Revises: 8a29d205351e
Create Date: 2020-08-29 13:25:54.126617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f62addb702d0'
down_revision = '8a29d205351e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_orders', sa.Column('special', sa.SmallInteger(), nullable=True, comment='0.默认正常商品；1.有仓储分装流程的商品'))
    op.alter_column('items_orders', 'rates',
               existing_type=mysql.VARCHAR(length=64),
               comment='评分',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_orders', 'rates',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='评分',
               existing_nullable=True)
    op.drop_column('items_orders', 'special')
    # ### end Alembic commands ###
